KEY BINDINGS                                                                                                                                                                                                                                                                   │
------------                                                                                                                                                                                                                                                                   │
                                                                                                                                                                                                                                                                               │
To help navigate through the file there are many hotkeys that should                                                                                                                                                                                                           │
make it easy to zero-in on a specific section of the file or scan                                                                                                                                                                                                              │
through the file.                                                                                                                                                                                                                                                              │
                                                                                                                                                                                                                                                                               │
  ?                 View/leave this help message.                                                                                                                                                                                                                              │
  q                 Leave the current view or quit the program when in                                                                                                                                                                                                         │
                    the log file view.                                                                                                                                                                                                                                         │
                                                                                                                                                                                                                                                                               │
  g/home            Move to the top of the file.                                                                                                                                                                                                                               │
  G/end             Move to the end of the file.  If the view is already                                                                                                                                                                                                       │
                    at the end, it will move to the last line.                                                                                                                                                                                                                 │
  space/pgdn        Move down a page.                                                                                                                                                                                                                                          │
  b/bs/pgup         Move up a page.                                                                                                                                                                                                                                            │
  j/cr/down-arrow   Move down a line.                                                                                                                                                                                                                                          │
  k/up-arrow        Move up a line.                                                                                                                                                                                                                                            │
  h/left-arrow      Move to the left.                                                                                                                                                                                                                                          │
  l/right-arrow     Move to the right.                                                                                                                                                                                                                                         │
  H/Shift+left      Move to the left by a smaller increment.                                                                                                                                                                                                                   │
  L/Shift+right     Move to the right by a smaller increment.                                                                                                                                                                                                                  │
                                                                                                                                                                                                                                                                               │
  e/E               Move to the next/previous error.                                                                                                                                                                                                                           │
  w/W               Move to the next/previous warning.                                                                                                                                                                                                                         │
  n/N               Move to the next/previous search hit.                                                                                                                                                                                                                      │
  f/F               Move to the next/previous file.  In the log view, this                                                                                                                                                                                                     │
                    moves to the next line from a different file.  In the                                                                                                                                                                                                      │
                    text view, this rotates the view to the next file.                                                                                                                                                                                                         │
                                                                                                                                                                                                                                                                               │
  >/<               Move horizontally to the next/previous search hit.                                                                                                                                                                                                         │
                                                                                                                                                                                                                                                                               │
  P                 Switch to/from the pretty-printed view of the log or text                                                                                                                                                                                                  │
                    files currently displayed.  In this view, structured data,                                                                                                                                                                                                 │
                    such as XML, will be reformatted to make it easier to read.                                                                                                                                                                                                │
                                                                                                                                                                                                                                                                               │
  t                 Switch to/from the text file view.  The text file view is                                                                                                                                                                                                  │
                    for any files that are not recognized as log files.                                                                                                                                                                                                        │
                                                                                                                                                                                                                                                                               │
  Ctrl-L            (Lo-fi mode) Exit screen-mode and write the                                                                                                                                                                                                                │
                    displayed log lines in plain text to the terminal                                                                                                                                                                                                          │
                    until a key is pressed.  Useful for copying long lines                                                                                                                                                                                                     │
                    from the terminal without picking up any of the extra                                                                                                                                                                                                      │
                    decorations.

                                                                                                                                                                                                                                                                              │
  :<command>        Execute an internal command.  The commands are                                                                                                                                                                                                             │
                    listed below.  History is also supported in this                                                                                                                                                                                                           │
                    context as well as tab-completion for commands and                                                                                                                                                                                                         │
                    some arguments.  The result of the command                                                                                                                                                                                                                 │
                    replaces the command you typed.                                                                                                                                                                                                                            │
                                                                                                                                                                                                                                                                               │
  ;<sql>            Execute an SQL query.  Most supported log file                                                                                                                                                                                                             │
                    formats provide a sqlite virtual table backend                                                                                                                                                                                                             │
                    that can be used in queries.  See the SQL section                                                                                                                                                                                                          │
                    below for more information.                                                                                                                                                                                                                                │
                                                                                                                                                                                                                                                                               │
  CTRL+]            Abort command-line entry started with '/', ':', or ';'.                                                                                                                                                                                                    │
                                                                                                                                                                                                                                                                               │
  y/Y               Move forward/backward through the log view based on the                                                                                                                                                                                                    │
                    "log_line" column in the SQL result view.                                                                                                                                                                                                                  │
                                                                                                                                                                                                                                                                               │
  v                 Switch to/from the SQL result view.                                                                                                                                                                                                                        │
                                                                                                                                                                                                                                                                               │
  V                 Switch between the log and SQL result views while                                                                                                                                                                                                          │
                    keeping the top line number in the log view in                                                                                                                                                                                                             │
                    sync with the log_line column in the SQL view.                                                                                                                                                                                                             │
                    For example, doing a query that selects for                                                                                                                                                                                                                │
                    "log_idle_msecs" and "log_line", you can move the                                                                                                                                                                                                          │
                    top of the SQL view to a line and hit 'V' to switch                                                                                                                                                                                                        │
                    to the log view and move to the line number that was                                                                                                                                                                                                       │
                    selected in the "log_line" column.                                                                                                                                                                                                                         │
                                                                                                                                                                                                                                                                               │
  TAB/Shift+TAB     In the SQL result view, cycle through the columns that                                                                                                                                                                                                     │
                    are graphed.  Initially, all number values are displayed                                                                                                                                                                                                   │
                    in a stacked graph.  Pressing TAB will change the display                                                                                                                                                                                                  │
                    to only graph the first column.  Repeatedly pressing TAB                                                                                                                                                                                                   │
                    will cycle through the columns until they are all graphed                                                                                                                                                                                                  │
                    again.                                                                                                                                                                                                                                                     │
                                                                                                                                                                                                                                                                               │
  p                 Enable or disable the display of the fields that the                                                                                                                                                                                                       │
                    log message parser knows about or has discovered.                                                                                                                                                                                                          │
                    This overlay is temporarily enabled when the semicolon                                                                                                                                                                                                     │
                    key (;) is pressed so that it is easier to write queries.                                                                                                                                                                                                  │
                                                                                                                                                                                                                                                                               │
  X                 Close the current text file or log file.                                                                                                                                                                                                                   │
                                                                                                                                                                                                                                                                               │
  CTRL-R            Reset the session state.  This will save the current                                                                                                                                                                                                       │
                    session state (filters, highlights) and then reset the                                                                                                                                                                                                     │
                    state to the factory default.                                                                                                                                                                                                                              │
                                                                                                                                                                                                                                                                               │
  CTRL-W            Toggle word-wrapping.                                                                                                                                                                                                                                      │
                                                                                                                                                                                                                                                                               │
  F2                Toggle mouse support.

  s/S               Move to the next/previous "slow down" in the log message                                                                                                                                                                                                   │
                    rate.  A slow down is detected by measuring how quickly                                                                                                                                                                                                    │
                    the message rate has changed over the previous several                                                                                                                                                                                                     │
                    messages.  For example, if one message is logged every                                                                                                                                                                                                     │
                    second for five seconds and then the last message arrives                                                                                                                                                                                                  │
                    five seconds later, the last message will be highlighted                                                                                                                                                                                                   │
                    as a slow down.                                                                                                                                                                                                                                            │
                                                                                                                                                                                                                                                                               │
  i                 View/leave a histogram of the log messages over                                                                                                                                                                                                            │
                    time.  The histogram counts the number of                                                                                                                                                                                                                  │
                    displayed log lines for each bucket of time.  The                                                                                                                                                                                                          │
                    bars are layed out horizontally with colored                                                                                                                                                                                                               │
                    segments representing the different log levels.                                                                                                                                                                                                            │
                    You can use the 'z' hotkey to change the size of                                                                                                                                                                                                           │
                    the time buckets (e.g. ten minutes, one hour, one                                                                                                                                                                                                          │
                    day).                                                                                                                                                                                                                                                      │
                                                                                                                                                                                                                                                                               │
  I                 Switch between the log and histogram views while                                                                                                                                                                                                           │
                    keeping the time displayed at the top of each view                                                                                                                                                                                                         │
                    in sync.  For example, if the top line in the log                                                                                                                                                                                                          │
                    view is "11:40", hitting 'I' will switch to the                                                                                                                                                                                                            │
                    histogram view and scrolled to display "11:00" at                                                                                                                                                                                                          │
                    the top (if the zoom level is hours).                                                                                                                                                                                                                      │
                                                                                                                                                                                                                                                                               │
  z/Shift Z         Zoom in or out one step in the histogram view.                                                                                                                                                                                                             │
                                                                                                                                                                                                                                                                               │
  /<regexp>         Start a search for the given regular expression.                                                                                                                                                                                                           │
                    The search is live, so when there is a pause in                                                                                                                                                                                                            │
                    typing, the currently running search will be                                                                                                                                                                                                               │
                    canceled and a new one started.  History is                                                                                                                                                                                                                │
                    maintained for your searches so you can rerun them                                                                                                                                                                                                         │
                    easily.  Words that are currently displayed are also                                                                                                                                                                                                       │
                    available for tab-completion, so you can easily                                                                                                                                                                                                            │
                    search for values without needing to copy-and-paste                                                                                                                                                                                                        │
                    the string.  If there is an error encountered while                                                                                                                                                                                                        │
                    trying to interpret the expression, the error will                                                                                                                                                                                                         │
                    be displayed in red on the status line.  While the                                                                                                                                                                                                         │
                    search is active, the 'hits' field in the status                                                                                                                                                                                                           │
                    line will be green, when finished it will turn                                                                                                                                                                                                             │
                    back to black.                                                                                                                                                                                                                                             │
                                                                                                                                                                                                                                                                               │
                    Note: The regular expression format used by is PCRE                                                                                                                                                                                                        │
                    (Perl-Compatible Regular Expressions).  For example,                                                                                                                                                                                                       │
                    if you wanted to search for ethernet device names,                                                                                                                                                                                                         │
                    regardless of their ID number, you can type:                                                                                                                                                                                                               │
                                                                                                                                                                                                                                                                               │
                      eth\d+                                                                                                                                                                                                                                                   │
                                                                                                                                                                                                                                                                               │
                    You can find more information about Perl regular                                                                                                                                                                                                           │
                    expressions at:                                                                                                                                                                                                                                            │
                                                                                                                                                                                                                                                                               │
                      http://perldoc.perl.org/perlre.html                                                                                                                                                                                                                      │
                                                                                                                                                                                                                                                                               │
                    If the search string is not valid PCRE, a search                                                                                                                                                                                                           │
                    is done for the exact string instead of doing a                                                                                                                                                                                                            │
                    regex search.


  o/O               Move forward/backward 60 minutes from the current                                                                                                                                                                                                          │
                    position in the log file.                                                                                                                                                                                                                                  │
                                                                                                                                                                                                                                                                               │
  d/D               Move forward/backward 24 hours from the current                                                                                                                                                                                                            │
                    position in the log file.                                                                                                                                                                                                                                  │
                                                                                                                                                                                                                                                                               │
  1-6/Shift 1-6     Move to the next/previous n'th ten minute of the                                                                                                                                                                                                           │
                    hour.  For example, '4' would move to the first                                                                                                                                                                                                            │
                    log line in the fortieth minute of the current                                                                                                                                                                                                             │
                    hour in the log.  And, '6' would move to the next                                                                                                                                                                                                          │
                    hour boundary.                                                                                                                                                                                                                                             │
                                                                                                                                                                                                                                                                               │
  0/Shift 0         Move to the next/previous day boundary.                                                                                                                                                                                                                    │
                                                                                                                                                                                                                                                                               │
  r/R               Move forward/backward based on the relative time that                                                                                                                                                                                                      │
                    was last used with the 'goto' command.  For example,                                                                                                                                                                                                       │
                    executing ':goto a minute later' will move the log view                                                                                                                                                                                                    │
                    forward a minute and then pressing 'r' will move it                                                                                                                                                                                                        │
                    forward a minute again.  Pressing 'R' will then move the                                                                                                                                                                                                   │
                    view in the opposite direction, so backwards a minute.                                                                                                                                                                                                     │
                                                                                                                                                                                                                                                                               │
  m                 Mark/unmark the line at the top of the display.                                                                                                                                                                                                            │
                    The line will be highlighted with reverse video to                                                                                                                                                                                                         │
                    indicate that it is a user bookmark.  You can use                                                                                                                                                                                                          │
                    the 'u' hotkey to iterate through marks you have                                                                                                                                                                                                           │
                    added.                                                                                                                                                                                                                                                     │
                                                                                                                                                                                                                                                                               │
  M                 Mark/unmark all the lines between the top of the                                                                                                                                                                                                           │
                    display and the last line marked/unmarked.                                                                                                                                                                                                                 │
                                                                                                                                                                                                                                                                               │
  J                 Mark/unmark the next line after the previously                                                                                                                                                                                                             │
                    marked line.                                                                                                                                                                                                                                               │
                                                                                                                                                                                                                                                                               │
  K                 Like 'J' except it toggles the mark on the                                                                                                                                                                                                                 │
                    previous line.                                                                                                                                                                                                                                             │
                                                                                                                                                                                                                                                                               │
  c                 Copy the marked text to the X11 selection buffer or OS X                                                                                                                                                                                                   │
                    clipboard.                                                                                                                                                                                                                                                 │
                                                                                                                                                                                                                                                                               │
  C                 Clear all marked lines.                                                                                                                                                                                                                                    │
                                                                                                                                                                                                                                                                               │
  u/U               Move forward/backward through any user bookmarks                                                                                                                                                                                                           │
                    you have added using the 'm' key.  This hotkey will                                                                                                                                                                                                        │
                    also jump to the start of any log partitions that have                                                                                                                                                                                                     │
                    been created with the 'partition-name' command.                                                                                                                                                                                                            │
                                                                                                                                                                                                                                                                               │
  T                 Toggle the display of the "elapsed time" column that shows                                                                                                                                                                                                 │
                    the time elapsed since the beginning of the logs or the                                                                                                                                                                                                    │
                    offset from the previous bookmark.  Sharp changes in the                                                                                                                                                                                                   │
                    message rate are highlighted by coloring the separator                                                                                                                                                                                                     │
                    between the time column and the log message.  A red                                                                                                                                                                                                        │
                    highlight means the message rate has slowed down and green                                                                                                                                                                                                 │
                    means it has sped up.  You can use the "s/S" hotkeys to                                                                                                                                                                                                    │
                    scan through the slow downs.  o/O               Move forward/backward 60 minutes from the current                                                                                                                                                                                                          │
                    position in the log file.                                                                                                                                                                                                                                  │
                                                                                                                                                                                                                                                                               │
  d/D               Move forward/backward 24 hours from the current                                                                                                                                                                                                            │
                    position in the log file.                                                                                                                                                                                                                                  │
                                                                                                                                                                                                                                                                               │
  1-6/Shift 1-6     Move to the next/previous n'th ten minute of the                                                                                                                                                                                                           │
                    hour.  For example, '4' would move to the first                                                                                                                                                                                                            │
                    log line in the fortieth minute of the current                                                                                                                                                                                                             │
                    hour in the log.  And, '6' would move to the next                                                                                                                                                                                                          │
                    hour boundary.                                                                                                                                                                                                                                             │
                                                                                                                                                                                                                                                                               │
  0/Shift 0         Move to the next/previous day boundary.                                                                                                                                                                                                                    │
                                                                                                                                                                                                                                                                               │
  r/R               Move forward/backward based on the relative time that                                                                                                                                                                                                      │
                    was last used with the 'goto' command.  For example,                                                                                                                                                                                                       │
                    executing ':goto a minute later' will move the log view                                                                                                                                                                                                    │
                    forward a minute and then pressing 'r' will move it                                                                                                                                                                                                        │
                    forward a minute again.  Pressing 'R' will then move the                                                                                                                                                                                                   │
                    view in the opposite direction, so backwards a minute.                                                                                                                                                                                                     │
                                                                                                                                                                                                                                                                               │
  m                 Mark/unmark the line at the top of the display.                                                                                                                                                                                                            │
                    The line will be highlighted with reverse video to                                                                                                                                                                                                         │
                    indicate that it is a user bookmark.  You can use                                                                                                                                                                                                          │
                    the 'u' hotkey to iterate through marks you have                                                                                                                                                                                                           │
                    added.                                                                                                                                                                                                                                                     │
                                                                                                                                                                                                                                                                               │
  M                 Mark/unmark all the lines between the top of the                                                                                                                                                                                                           │
                    display and the last line marked/unmarked.                                                                                                                                                                                                                 │
                                                                                                                                                                                                                                                                               │
  J                 Mark/unmark the next line after the previously                                                                                                                                                                                                             │
                    marked line.                                                                                                                                                                                                                                               │
                                                                                                                                                                                                                                                                               │
  K                 Like 'J' except it toggles the mark on the                                                                                                                                                                                                                 │
                    previous line.                                                                                                                                                                                                                                             │
                                                                                                                                                                                                                                                                               │
  c                 Copy the marked text to the X11 selection buffer or OS X                                                                                                                                                                                                   │
                    clipboard.                                                                                                                                                                                                                                                 │
                                                                                                                                                                                                                                                                               │
  C                 Clear all marked lines.                                                                                                                                                                                                                                    │
                                                                                                                                                                                                                                                                               │
  u/U               Move forward/backward through any user bookmarks                                                                                                                                                                                                           │
                    you have added using the 'm' key.  This hotkey will                                                                                                                                                                                                        │
                    also jump to the start of any log partitions that have                                                                                                                                                                                                     │
                    been created with the 'partition-name' command.                                                                                                                                                                                                            │
                                                                                                                                                                                                                                                                               │
  T                 Toggle the display of the "elapsed time" column that shows                                                                                                                                                                                                 │
                    the time elapsed since the beginning of the logs or the                                                                                                                                                                                                    │
                    offset from the previous bookmark.  Sharp changes in the                                                                                                                                                                                                   │
                    message rate are highlighted by coloring the separator                                                                                                                                                                                                     │
                    between the time column and the log message.  A red                                                                                                                                                                                                        │
                    highlight means the message rate has slowed down and green                                                                                                                                                                                                 │
                    means it has sped up.  You can use the "s/S" hotkeys to                                                                                                                                                                                                    │
                    scan through the slow downs.
