#!bin/bash

# ------------------------------------------------------------------------------
PDD
# ------------------------------------------------------------------------------
'ROADOFTHEDEAD_TLR_F_FR-XX_FR_51_2K_20151030_OV'
'LeGrandPartage_TSR-Concierge_F_FR-XX_FR_51_2K_WBD_20151014_TST_IOP_OV'
'FallOut4_ADV-30_F_FR-XX_FR_51_2K_CJP_20151027_TST_OV'
'MICROSOFT_ADV_F_FR-XX_FR_51_2K_20151030_ECL_OV'





# ------------------------------------------------------------------------------
COMPLEXE
# ------------------------------------------------------------------------------


CARROZ D ARACHE CHOUCA



SMARTJOG_ONLY(){
  aix en provence cezanne
  manosque Lido (dejust)
}


USB_ONLY(){
  carbon blanc favol
}
